GET http://localhost:3000/songs.json


###
GET http://localhost:3000/songs/3.json

###

POST http://localhost:3000/songs.json
Content-Type: application/json

{
  "title": "Toy",
  "artist": "Netta",
  "year": 2018,
  "country": "Israel"
}

###
PATCH http://localhost:3000/songs/5.json
Content-Type: application/json

{
  "album": "Bassa Sababa"
}

###
DELETE http://localhost:3000/songs/5.json